name: Publish Alpha package

on:
  push:
    branches:
      - main

jobs:
  alpha-publish:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest
    env:
      CONFIG_TYPE: "UAT"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn add husky --dev

      - name: Build the package
        run: yarn build

      - name: Stash uncommitted changes
        run: git stash --include-untracked

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump package version to alpha
        run: |
          yarn version --prerelease --preid=alpha.$(git rev-parse --short HEAD)

      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          config-name: release-drafter.yaml
          disable-autolabeler: true
          tag: ${{ env.RELEASE_VERSION }}
          release: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
