name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    contents: write
      packages: write
      pull-requests: write

    runs-on: ubuntu-latest
    env:
      CONFIG_TYPE: "UAT"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn add husky --dev

      - name: Build the package
        run: yarn build

      - name: Stash uncommitted changes
        run: git stash --include-untracked

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Publish to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
