name: Publish Package to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    permissions:
      contents: write
      packages: write
      pull-requests: write

    runs-on: ubuntu-latest
    env:
      CONFIG_TYPE: "UAT"
      NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - run: npm install husky

      - name: Build the package
        run: npm run build

      - name: Stash uncommitted changes
        run: git stash --include-untracked

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}

      - name: Publish to NPM
        run: npm publish --access public --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
