name: MUI-Dialog-Storybook-Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    name: Build and Publish Storybook
    runs-on: ubuntu-latest
    env:
      CONFIG_TYPE: "PRODUCTION"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nodejs, Install Dependencies, and Build Storybook
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - run: yarn install --immutable

      - run: yarn build-storybook

      - name: Install aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload files to S3 with AWS CLI
        run: |
          aws sts get-caller-identity
          aws s3 sync ./storybook-static s3://storybook.viplatform.net/mui-dialog

      - name: Store AWS credentials in a file
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY }}" > aws_credentials.txt
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> aws_credentials.txt

      - name: Upload AWS credentials file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-aws-credentials
          path: aws_credentials.txt
 
